### ISSUE TITLE
Error rendering tables inside lists

### ISSUE THREAD

**Issue by mondeja** [mondeja/mdpo#111]
## Input

```markdown
- A list item
   + A nested list item
      * A double nested list item
      * Another double nested list item
         
         | Syntax      | Description  | Style | A    |
         | ----------- | :----------- | ----: | :--: |
         | Header      | Title        | Foo   | B    |
         | Paragraph   | Text         | Bar   | C    |
```

## Error

```
Traceback (most recent call last):
  File "mdpo/po2md/__main__.py", line 119, in <module>
    main()
  File "mdpo/po2md/__main__.py", line 115, in main
    sys.exit(run(args=sys.argv[1:])[1])  # pragma: no cover
  File "mdpo/po2md/__main__.py", line 99, in run
    output = pofile_to_markdown(
  File "/.../mdpo/po2md/__init__.py", line 776, in pofile_to_markdown
    return Po2Md(
  File "/.../mdpo/po2md/__init__.py", line 712, in translate
    parser.parse(
  File "/.../mdpo/po2md/__init__.py", line 547, in leave_block
    align = self._current_thead_aligns.pop(0)
IndexError: pop from empty list
```

**Comment by mondeja** [comment]
Fixed in [v0.3.41](https://github.com/mondeja/mdpo/releases/tag/v0.3.41).
